In [8]:
import numpy as np

i)	Create a one-dimensional array and perform  all operations on it.

In [9]:
a = np.arange(1,6)
print(a+2)
print(a*2)
print(a-2)
print(np.sqrt(a))
print(np.exp(a))

[3 4 5 6 7]
[ 2  4  6  8 10]
[-1  0  1  2  3]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


ii)	Create multi-dimensional arrays and find its shape and dimension 

In [10]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("shape :",a.shape)
print("dimension :",a.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape : (3, 3)
dimension : 2


iii)	Create a matrix full of zeros and ones 

In [11]:
a = np.zeros((3,3))
b = np.ones((3,3))
print(a,"\n",b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


iv)	Reshape and flatten data in the array 

In [12]:
a = np.arange(1,10)
print(a)
a = a.reshape(3,3)
print(a)
a = a.flatten() # np.flatten(array)
print(a)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


v)	Perform arithmetic operations on multi-dimensional  arrays

In [13]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)
print(a+b)
print(a*b)
print(a-b)
print(a+5)
print(a%b)

[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


vi)	Append data vertically and horizontally 

In [14]:
a = np.arange(1,10).reshape(3,3)
b = np.array([1,2,3]).reshape(1,3)
print(np.append(a,b,axis=0))
print(np.append(a,b.T,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
[[1 2 3 1]
 [4 5 6 2]
 [7 8 9 3]]


In [33]:
a = np.array([[1, 1], [2, 2], [3, 3]])
print(a)
np.insert(a, 1, 5)

[[1 1]
 [2 2]
 [3 3]]


array([1, 5, 1, 2, 2, 3, 3])

vii)	Apply indexing and slicing on array 

In [15]:
a = np.arange(1,28).reshape(3,3,3)
print(a,"\n---------------")
print(a[1,2])
print()
print(a[1:3,2])
print()
print(a[2,1,2])
print()

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] 
---------------
[16 17 18]

[[16 17 18]
 [25 26 27]]

24



viii)	Use statistical functions on array - Min, Max, Mean, Median and Standard Deviation 

In [16]:
a = np.arange(1,6)
print(a.max())
print(a.min())
print(a.mean())
print(np.median(a))
print(a.std())

5
1
3.0
3.0
1.4142135623730951


ix)	Dot  matrix product of two arrays 

In [17]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(1,4).reshape(3,1)
print(np.dot(a,b))

[[14]
 [32]
 [50]]


x)	Compute the Eigen values of a matrix 

In [18]:
a = np.arange(2,11).reshape(3,3)
print(np.linalg.eig(a)[0])

[ 1.89498744e+01 -9.49874371e-01 -7.57759754e-16]


xi)	Solve a linear matrix equation such as 3 * x0 + x1 = 9, x0 + 2 * x1 = 8 

In [19]:
# 3 * x0 + x1 = 9, x0 + 2 * x1 = 8 
a = np.array([[3,1],[1,2]])
b = np.array([9,8])
print(np.linalg.solve(a,b))

[2. 3.]


xii)	Compute the multiplicative inverse of a matrix 

In [20]:
a = np.arange(2,6).reshape(2,2)
print(a)
print(np.linalg.inv(a))

[[2 3]
 [4 5]]
[[-2.5  1.5]
 [ 2.  -1. ]]


xiii)	Compute the rank of a matrix 

In [36]:
a = np.arange(2,6).reshape(2,2);print(a)
print(np.linalg.matrix_rank(a))

[[2 3]
 [4 5]]
2


xiv)	 Compute the determinant of an array

In [22]:
a = np.arange(2,6).reshape(2,2);print(a)
print(np.linalg.det(a))

[[2 3]
 [4 5]]
-2.0


xv)	Perform transpose and change of axes operations on arrays.

In [41]:
a = np.arange(1,10).reshape(3,3)
print(a)
print(a.T)
print(np.swapaxes(a,0,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


xvi)	Perform splitting operations on arrays.

In [24]:
a = np.arange(1,13).reshape(2,6)
b = np.arange(11,23).reshape(6,2)
print(np.hsplit(a,3))
print(np.vsplit(b,3))

[array([[1, 2],
       [7, 8]]), array([[ 3,  4],
       [ 9, 10]]), array([[ 5,  6],
       [11, 12]])]
[array([[11, 12],
       [13, 14]]), array([[15, 16],
       [17, 18]]), array([[19, 20],
       [21, 22]])]


1.How to convert an array of strings to an array of floats in numpy?

In [25]:
a = np.array(['1.1','1.2','1.3','1.4'])
print(a)
a = a.astype(float)
print(a)

['1.1' '1.2' '1.3' '1.4']
[1.1 1.2 1.3 1.4]


2.Extracting first n columns of a Numpy matrix

In [26]:
a = np.arange(1,26).reshape(5,5)
n = int(input("Enter the no. of columns : "))
print(a[:,:n])

Enter the no. of columns : 


ValueError: invalid literal for int() with base 10: ''

3.How to calculate the sum of every row in a NumPy array in Python?

In [ ]:
a = np.arange(1,26).reshape(5,5)
print(a)
print("sum of every row : ",a.sum(axis=1))

4. How to check all elements are NaN in a NumPy Array in Python?

In [ ]:
import numpy as np

a = np.array([1,2,3,np.nan,np.nan])

print(np.isnan(a).all())
print(np.isnan(a))

5. How to multiply each element of Numpy array in Python?

In [ ]:

the_array =np.array([[1, 2, 3], [1, 2, 3]])
 
prod =np.prod(the_array)
print(prod)


6. Scalar Arithmetic Operations on NumPy Array

In [ ]:
a = np.arange(1,10).reshape(3,3)
print(a+3)
print(a-3)
print(a*3)
print(a/3)
print(a%3)
print(a//3)

7. How to check for NaN elements in a NumPy Array in Python?

In [ ]:
import numpy as np

a = np.array([1,2,3,np.nan,np.nan])

print(np.isnan(a).all())
print(np.isnan(a))

8. NumPy Element Wise Mathematical Operations

In [ ]:

array1 =np.array([[10,20,30],[40,50,60]])
array2 =np.array([[2,3,4],[4,6,8]])
array3 =np.array([[-2,3.5, -4],[4.05, -6,8]])
 
print(array1+array2)
print("-" * 40)
 
print(np.power(array1, array2))
print("-" * 40)
 
print(np.remainder((array2),5))
print("-" * 40)
 
print(1/(array3))
print("-" * 40)
 
print(np.sign(array3))
print("-" * 40)
 
print(np.ceil(array3))
print("-" * 40)
 
print(np.round(array3))
print("-" * 40)


9. How to count frequency of unique values in a NumPy array in Python?

In [ ]:

the_array =np.array([9, 7, 4, 7, 3, 5, 9])
 
frequencies =np.asarray((np.unique(the_array, return_counts=True))).T
print(frequencies)


10. Write a NumPy program to get the indices of the sorted elements of a given array.

In [ ]:
a = np.array([3,6,45,3,4,3,2,4,5,23,2])
print("indices are : ",np.argsort(a))

11. How to print a full NumPy array without truncation in Python?

In [ ]:

np.set_printoptions(threshold=np.inf)
 
the_array =np.arange(100)
print(the_array)


12. How to get the transpose of a NumPy array in Python?

In [ ]:
a = np.arange(1,7).reshape(3,2)
print(a)
print(a.T)
print(np.transpose(a))

13. How do you replace items that satisfy a condition with another value in Numpy array?

In [ ]:
a = np.arange(1,7).reshape(3,2)
print(a)
print(np.where(a>3,2,1))