# 1.Load the data in the file Iris. txt in a 2-D array called iris.

In [1]:
import numpy as np
import pandas as pd
iris = np.loadtxt('iris.txt',delimiter=',',dtype='f')
# print(iris)

# 2.Drop column whose index = 4 from the array iris.

In [2]:
print(np.delete(iris,4,axis=1))

[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.

# 3. Display the shape, dimensions and size of iris.

In [3]:
print("shape of iris : ",iris.shape)
print("dimension of iris : ",iris.ndim)

shape of iris :  (149, 5)
dimension of iris :  2


# 4. Split iris into three 2-D arrays, each array for a different species. Call them irisl, iris2, iris3.
# 5. Print the three arrays irisl, iris2, iris3

In [4]:
iris1 = iris[iris[:,4] == 1]
iris2 = iris[iris[:,4] == 2]
iris3 = iris[iris[:,4] == 3]
print(iris1,iris2,iris3)

[[4.9 3.  1.4 0.2 1. ]
 [4.7 3.2 1.3 0.2 1. ]
 [4.6 3.1 1.5 0.2 1. ]
 [5.  3.6 1.4 0.2 1. ]
 [5.4 3.9 1.7 0.4 1. ]
 [4.6 3.4 1.4 0.3 1. ]
 [5.  3.4 1.5 0.2 1. ]
 [4.4 2.9 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [5.4 3.7 1.5 0.2 1. ]
 [4.8 3.4 1.6 0.2 1. ]
 [4.8 3.  1.4 0.1 1. ]
 [4.3 3.  1.1 0.1 1. ]
 [5.8 4.  1.2 0.2 1. ]
 [5.7 4.4 1.5 0.4 1. ]
 [5.4 3.9 1.3 0.4 1. ]
 [5.1 3.5 1.4 0.3 1. ]
 [5.7 3.8 1.7 0.3 1. ]
 [5.1 3.8 1.5 0.3 1. ]
 [5.4 3.4 1.7 0.2 1. ]
 [5.1 3.7 1.5 0.4 1. ]
 [4.6 3.6 1.  0.2 1. ]
 [5.1 3.3 1.7 0.5 1. ]
 [4.8 3.4 1.9 0.2 1. ]
 [5.  3.  1.6 0.2 1. ]
 [5.  3.4 1.6 0.4 1. ]
 [5.2 3.5 1.5 0.2 1. ]
 [5.2 3.4 1.4 0.2 1. ]
 [4.7 3.2 1.6 0.2 1. ]
 [4.8 3.1 1.6 0.2 1. ]
 [5.4 3.4 1.5 0.4 1. ]
 [5.2 4.1 1.5 0.1 1. ]
 [5.5 4.2 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [5.  3.2 1.2 0.2 1. ]
 [5.5 3.5 1.3 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [4.4 3.  1.3 0.2 1. ]
 [5.1 3.4 1.5 0.2 1. ]
 [5.  3.5 1.3 0.3 1. ]
 [4.5 2.3 1.3 0.3 1. ]
 [4.4 3.2 1.3 0.2 1. ]
 [5.  3.5 1.6 0.6 1. ]
 [5.1 3.8 1

# 6. Create a 1-D array header having elements "sepal length", "sepal width", "petal length", "petal width", "Species No" in that order.
# 7. Display the array header.

In [5]:
header = "sepal length, sepal width, petal length, petal width, Species No"
np.savetxt('iris.txt',iris,delimiter=',',header = header)
print(header)

sepal length, sepal width, petal length, petal width, Species No


# 8. Find the max, min, mean and standard deviation for the columns of the iris and store the results in the arrays iris_max, iris_min, iris_avg, iris_std, iris_ var respectively. The results must be rounded to not more than two decimal places.

In [6]:
iris_max = np.round(iris.max(axis=0),2)
iris_min = np.round(iris.min(axis=0),2)
iris_avg = np.round(iris.mean(axis=0),2)
iris_std = np.round(iris.std(axis=0),2)
iris_var = np.round(iris.var(axis=0),2)
print(iris_max, iris_min, iris_avg, iris_std, iris_var )

[7.9 4.4 6.9 2.5 3. ] [4.3 2.  1.  0.1 1. ] [5.85 3.05 3.77 1.21 2.01] [0.83 0.43 1.75 0.76 0.82] [0.68 0.19 3.08 0.58 0.66]


# 10. Check the minimum value for sepal length, sepal width, petal length and petal width of the three species in comparison to the minimum value of sepal length, sepal width, petal length and petal width for the data set as a whole and fill the table below with True if the species value is greater than the dataset value and False otherwise.

In [7]:
iris1_min = np.round(iris1.min(axis=0),2)
iris2_min = np.round(iris2.min(axis=0),2)
iris3_min = np.round(iris3.min(axis=0),2)
print(iris1_min > iris_min)
print(iris2_min > iris_min)
print(iris3_min > iris_min)

[False  True False False False]
[ True False  True  True  True]
[ True  True  True  True  True]


# 11. Compare Iris setosa's average sepal width to that of Iris virginica.
# 12. Compare Iris setosa's average petal length to that of Iris virginica.
# 13. Compare Iris setosa's average petal width to that of Iris virginica.


In [8]:
print(iris1[:,1].mean() > iris3[:,1].mean())
print(iris1[:,2].mean() > iris3[:,2].mean())
print(iris1[:,3].mean() > iris3[:,3].mean())

True
False
False


# 14. Save the array iris_avg in a comma separated file named Iris MeanValues.txt on the hard disk.

In [9]:
np.savetxt('Iris MeanValues.txt',iris_avg.reshape(1,5),delimiter=",",fmt="%.2f",header="iris_avg")

# 15. Save the arrays iris_max, iris_avg, iris_min in a comma separated file named IrisStat.txt on the hard disk.

In [10]:
IrisStat = np.array((iris_max, iris_avg, iris_min)).T
np.savetxt('IrisStat.txt',IrisStat,delimiter=',',header = "iris_max, iris_avg, iris_min",fmt="%.2f")