In [5]:
import numpy as np

a = np.arange(1,6,1)
b = np.ones((3,2))
c = np.zeros((2,2))
d = np.eye(3,k=-1)
e = np.identity(2)
f = np.linspace(1.5,5.6,4)
g = np.random.random((2,2))
h = np.random.normal(0,1,(2,2))
i = np.random.randint(2,20,(2,2))
j = np.empty(3)
k = np.identity(3)
l = np.full((1,2),12)
print('a : \n',a)
print('b : \n',b)
print('c : \n',c)
print('d : \n',d)
print('e : \n',e)
print('f : \n',f)
print('g : \n',g)
print('h : \n',h)
print('i : \n',i)
print('j : \n',j)
print('k : \n',k)
print('l : \n',l)

a : 
 [1 2 3 4 5]
b : 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
c : 
 [[0. 0.]
 [0. 0.]]
d : 
 [[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
e : 
 [[1. 0.]
 [0. 1.]]
f : 
 [1.5        2.86666667 4.23333333 5.6       ]
g : 
 [[0.68655672 0.75659591]
 [0.88923758 0.82597408]]
h : 
 [[ 0.01543925 -0.95317886]
 [-0.18005616 -0.93299091]]
i : 
 [[ 2  6]
 [18 13]]
j : 
 [0.  0.5 1. ]
k : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
l : 
 [[12 12]]


In [8]:
a = np.arange(0,27).reshape(3,3,3)
print(a,"\n"*3)
print(a[:,:2,:])
print(a[1:-1])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 



[[[ 0  1  2]
  [ 3  4  5]]

 [[ 9 10 11]
  [12 13 14]]

 [[18 19 20]
  [21 22 23]]]
[[[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [ ]:
a = np.arange(1,10)
print(a)
print(a[2:-1])

[1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8]


In [ ]:
l=[1,2.,4,7,9]
a=np.array(l)
print(a)

[1. 2. 4. 7. 9.]


In [ ]:
a = np.array([1,2,2**10],dtype=np.int8)
print(a.dtype)

int8


In [ ]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)
print(numeric_strings)

[b'1.25' b'-9.6' b'42']


In [ ]:
print(a)
print(a.shape)

[1 2 0]
(3,)


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1., 2.], [3.,4.],[5., 6.]])
b = b.astype(int)
# print(b)
print(a@b)
print(np.dot(a,b))
print(np.matmul(a,b))

[[22 28]
 [49 64]]
[[22 28]
 [49 64]]
[[22 28]
 [49 64]]


In [ ]:
#Boolean Indexing

import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will'])
data = np.random.randn(5, 4)
print(data)
# print(names,names.dtype,data,data.dtype)

print(names == 'Bob')
print(names[names=='Bob'])

print(names != 'Bob')

mask = (names == 'Bob') | (names == 'Will')
print('mask=   ',mask)

print(data[data<0])
#set all of the negative values in data to 0 we need only do
data[data<0]=0
print(data)
#The boolean array must be of the same length as the axis it’s index

[[-0.48578591  0.08582309 -0.22890786  0.74367966]
 [ 0.2227182   0.03409533 -0.54111951 -1.08480516]
 [-0.74725277 -0.9612172  -2.07690119  1.21438563]
 [-0.94207427 -1.35470314  0.4028848   1.48851694]
 [-0.37539232  1.11200311  0.16119411 -0.95364217]]
[ True False False  True False]
['Bob' 'Bob']
[False  True  True False  True]
mask=    [ True False  True  True  True]
[-0.48578591 -0.22890786 -0.54111951 -1.08480516 -0.74725277 -0.9612172
 -2.07690119 -0.94207427 -1.35470314 -0.37539232 -0.95364217]
[[0.         0.08582309 0.         0.74367966]
 [0.2227182  0.03409533 0.         0.        ]
 [0.         0.         0.         1.21438563]
 [0.         0.         0.4028848  1.48851694]
 [0.         1.11200311 0.16119411 0.        ]]


In [8]:
#Basic Indexing and Slicing#

# array slices are views on the original array
#This means that the data is not copied, and any modifications
#to the view will be reflected in the source array.

#if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is
#propagated to the entire selection


###
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(a[1])
print(a[1,2], a[1][2])

temp=a[0].copy()
a[0]=66
print(a)

a[0]=temp
print(a)