In [38]:
import numpy as np

i)	Create a one-dimensional array and perform  all operations on it.

In [39]:
a = np.arange(1,6)
print(a+2)
print(a*2)
print(a-2)
print(np.sqrt(a))
print(np.exp(a))

[3 4 5 6 7]
[ 2  4  6  8 10]
[-1  0  1  2  3]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


ii)	Create multi-dimensional arrays and find its shape and dimension 

In [40]:
a = np.arange(1,10).reshape(3,3)
print(a)
print("shape :",a.shape)
print("dimension :",a.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape : (3, 3)
dimension : 2


iii)	Create a matrix full of zeros and ones 

In [41]:
a = np.zeros((3,3))
b = np.ones((3,3))
print(a,"\n",b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


iv)	Reshape and flatten data in the array 

In [42]:
a = np.arange(1,10)
print(a)
a = a.reshape(3,3)
print(a)
a = a.flatten() # np.flatten(array)
print(a)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


v)	Perform arithmetic operations on multi-dimensional  arrays

In [43]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)
print(a+b)
print(a*b)
print(a-b)
print(a+5)
print(a%b)

[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


vi)	Append data vertically and horizontally 

In [44]:
a = np.arange(1,10).reshape(3,3)
b = np.array([1,2,3]).reshape(1,3)
print(np.append(a,b,axis=0))
print(np.append(a,b.T,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
[[1 2 3 1]
 [4 5 6 2]
 [7 8 9 3]]


vii)	Apply indexing and slicing on array 

In [45]:
a = np.arange(1,28).reshape(3,3,3)
print(a,"\n---------------")
print(a[1,2])
print(a[1:3,2])
print(a[2,1,2])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] 
---------------
[16 17 18]
[[16 17 18]
 [25 26 27]]
24


viii)	Use statistical functions on array - Min, Max, Mean, Median and Standard Deviation 

In [46]:
a = np.arange(1,6)
print(a.max())
print(a.min())
print(a.mean())
print(np.median(a))
print(a.std())



5
1
3.0
3.0
1.4142135623730951


ix)	Dot  matrix product of two arrays 

In [47]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(1,4).reshape(3,1)
print(np.dot(a,b))

[[14]
 [32]
 [50]]


x)	Compute the Eigen values of a matrix 

In [48]:
a = np.arange(2,11).reshape(3,3)
print(np.linalg.eig(a)[0])

[ 1.89498744e+01 -9.49874371e-01 -7.57759754e-16]


xi)	Solve a linear matrix equation such as 3 * x0 + x1 = 9, x0 + 2 * x1 = 8 

In [49]:
# 3 * x0 + x1 = 9, x0 + 2 * x1 = 8 
a = np.array([[3,1],[1,2]])
b = np.array([9,8])
print(np.linalg.solve(a,b))

[2. 3.]


xii)	Compute the multiplicative inverse of a matrix 

In [50]:
a = np.arange(2,6).reshape(2,2)
print(np.linalg.inv(a))

[[-2.5  1.5]
 [ 2.  -1. ]]


xiii)	Compute the rank of a matrix 

In [51]:
a = np.arange(2,6).reshape(2,2)
print(np.linalg.matrix_rank(a))

2


xiv)	 Compute the determinant of an array

In [52]:
a = np.arange(2,6).reshape(2,2)
print(np.linalg.det(a))

-2.0


xv)	Perform transpose and change of axes operations on arrays.

In [53]:
a = np.arange(1,10).reshape(3,3)
print(a.T)
print(np.swapaxes(a,0,1))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


xvi)	Perform splitting operations on arrays.

In [54]:
a = np.arange(1,13).reshape(2,6)
b = np.arange(11,23).reshape(6,2)
print(np.hsplit(a,3))

print(np.vsplit(b,3))

[array([[1, 2],
       [7, 8]]), array([[ 3,  4],
       [ 9, 10]]), array([[ 5,  6],
       [11, 12]])]
[array([[11, 12],
       [13, 14]]), array([[15, 16],
       [17, 18]]), array([[19, 20],
       [21, 22]])]


1.How to convert an array of strings to an array of floats in numpy?

In [55]:
a = np.array(['1.1','1.2','1.3','1.4'])
print(a)
a = a.astype(float)
print(a)

['1.1' '1.2' '1.3' '1.4']
[1.1 1.2 1.3 1.4]


2.Extracting first n columns of a Numpy matrix

3.How to calculate the sum of every row in a NumPy array in Python?

4. How to check all elements are NaN in a NumPy Array in Python?

5. How to multiply each element of Numpy array in Python?

6. Scalar Arithmetic Operations on NumPy Array

7. How to check for NaN elements in a NumPy Array in Python?

8. NumPy Element Wise Mathematical Operations

9. How to count frequency of unique values in a NumPy array in Python?

10. Write a NumPy program to get the indices of the sorted elements of a given array.

11. How to print a full NumPy array without truncation in Python?

12. How to get the transpose of a NumPy array in Python?

13. How do you replace items that satisfy a condition with another value in Numpy array?